QolaMVC/Controllers/DineTimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QolaMVC.DAL;
using QolaMVC.Models;

namespace QolaMVC.Controllers
{
    public class DineTimeController : Controller
    {
        // GET: Suite
        public ActionResult List(string search,string column = "*", string value = "0")
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];
            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            List<NEW_DineTimeModel> l_Model;
            // List<NEW_DineTimeModel> l_Model = DineTimeDAL.GetAllDineTime();
            if (search == null || search == "")
            {
                l_Model = DineTimeDAL.GetDineTime_By_Column(column, value);
            }
            //List<NEW_SpecialDietModel> l_Model = SpecialDietDAL.GetAllSpecialDiet();
            else
            {
                l_Model = DineTimeDAL.GetDineTime_By_Search(search);
            }
            
            return View(l_Model);
            //return View();
        }

        // GET: Suite/Details/5
        public ActionResult Details(int id)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View();
        }

        // GET: Suite/Create
        public ActionResult AddDineTime()
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View();
        }

        // POST: Suite/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDineTime(NEW_DineTimeModel data)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            if (ModelState.IsValid)
            {
                DineTimeDAL.AddDineTime(data);
                TempData["notice"] = "Add Successfully";
                return RedirectToAction("List");
            }
            else
            {
                TempData["notice"] = "Add Failed";
                return RedirectToAction("List");
            }
            

        }

        // GET: Suite/Edit/5
        public ActionResult EditDineTime(int id)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View(DineTimeDAL.GetDineTime_By_Id(id));
        }

        // POST: Suite/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDineTime(int id, NEW_DineTimeModel data)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            if (ModelState.IsValid)
            {
                DineTimeDAL.EditDineTime(data, id);
                TempData["notice"] = "Edit Successfully";
                return RedirectToAction("List");
            }
            else
            {
                TempData["notice"] = "Edit Failed";
                return RedirectToAction("List");
            }
                
        }

        // GET: Suite/Delete/5
        public ActionResult DeleteDineTime(int id)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View(DineTimeDAL.GetDineTime_By_Id(id));
        }

        // POST: Suite/Delete/5
        [HttpPost]
        public ActionResult DeleteDineTime(int id, FormCollection collection)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            try
            {
                // TODO: Add delete logic here

                DineTimeDAL.DeleteDineTime(id);
                TempData["notice"] = "Delete Successfully";
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
    }
}

QolaMVC/Views/DineTime/AddDineTime.cshtml
@model QolaMVC.Models.NEW_DineTimeModel

@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
    .required_sign {
        color: red;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h3>@QolaMVC.Resources.Text.DineTime</h3>
                        </div>

                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("AddDineTime", "DineTime", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.DineTime<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.DineTime, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.DineTime, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.Code<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.ShortName, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.ShortName, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "DineTime")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Save_big</button>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")
        <script>
            $('form').submit(function (event) {
                if ($('#DineTime').val().trim() == '' || $('#ShortName').val().trim() == '') {
                    tempAlert("Mandatory Needed", 2000);
                    return false;

                }
                else {
                    form = this;
                    form.submit();
                }
            });
        </script>

QolaMVC/Views/DineTime/DeleteDineTime.cshtml
@model QolaMVC.Models.NEW_DineTimeModel
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h3>@QolaMVC.Resources.Text.AreYouSureYouWantToDeleteThisRecord</h3>
                        </div>

                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("DeleteDineTime", "DineTime", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="" class="col-form-label">@QolaMVC.Resources.Text.DineTime</label>
                                                <label class="form-control" style="width:70%;">@Model.DineTime</label>
                                                @Html.ValidationMessageFor(m => m.DineTime, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="" class="col-form-label">@QolaMVC.Resources.Text.ShortName</label>
                                                <label class="form-control" style="width:70%;">@Model.ShortName</label>
                                                @Html.ValidationMessageFor(m => m.ShortName, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "DineTime")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Delete_big</button>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")

QolaMVC/Views/DineTime/EditDineTime.cshtml
@model QolaMVC.Models.NEW_DineTimeModel
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
    .required_sign {
        color: red;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h3>@QolaMVC.Resources.Text.DineTime</h3>
                        </div>

                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("EditDineTime", "DineTime", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.DineTime<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.DineTime, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.DineTime, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.ShortName<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.ShortName, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.ShortName, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "DineTime")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Update_big</button>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")
        <script>
            $('form').submit(function (event) {
                if ($('#DineTime').val().trim() == '' || $('#ShortName').val().trim() == '') {
                    tempAlert("Mandatory Needed", 2000);
                    return false;

                }
                else {
                    form = this;
                    form.submit();
                }
            });
        </script>

QolaMVC/Views/DineTime/List.cshtml
@model List<QolaMVC.Models.NEW_DineTimeModel>
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>
    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <!-- START PAGE CONTENT WRAPPER -->
    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h3>@QolaMVC.Resources.Text.DineTime</h3>
                        </div>
                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->

                <div class="card">
                    <div class="card-block">

                        <div class="form-tabs mt-4">
                            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                              

                            </ul>
                            <div class="tab-content" id="pills-tabContent">
                                <div class="tab-pane fade show active" id="pills-active" role="tabpanel" aria-labelledby="pills-active-tab">

                                    <div class="row">
                                        <div class="py-4 text-left" style="display:inline-block;width:80%;">
                                            <form class="form-inline">
                                                @using (Html.BeginForm("List", "DineTime", FormMethod.Get))
                                                {

                                                    <div class="form-group pr-1">
                                                        <div class="input-group">
                                                            @*@Html.TextBox("value", null, new { @class = "form-control", @placeholder = "Search for" })*@
                                                            <input class="form-control" id="search_value" value="" />
                                                        </div>
                                                    </div>
                                                    <button type="button" class="btn btn-danger" onclick="search_DineTime()">@QolaMVC.Resources.Text.Search</button>
                                                }
                                            </form>
                                        </div>
                                        <div class="py-4 text-right" style="display:inline-block;width:15%;">
                                            <a class="btn btn-lg btn-primary" href="~/DineTime/AddDineTime">@QolaMVC.Resources.Text.AddNew</a>
                                        </div>
                                    </div>

                                    <table class="table table-bordered">
                                        <thead class="bg-primary">
                                            <tr>
                                                <th class="text-white">@QolaMVC.Resources.Text.SN</th>
                                                <th class="text-white">@QolaMVC.Resources.Text.DineTime</th>
                                                <th class="text-white">@QolaMVC.Resources.Text.ShortName</th>
                                                <th class="text-white">@QolaMVC.Resources.Text.Edit</th>
                                                <th class="text-white">@QolaMVC.Resources.Text.Delete_small</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{ int i = 1; }
                                            @{ foreach (var data in Model)
                                                {
                                                    <tr>
                                                        <td class="align-middle">@i</td>
                                                        <td class="align-middle">@data.DineTime</td>
                                                        <td class="align-middle">@data.ShortName</td>
                                                        <td class="align-middle">
                                                            <a class="btn btn-success btn-xs" href="~/DineTime/EditDineTime/@data.Id">
                                                                <i class="fa fa-pencil"></i>
                                                            </a>
                                                            @*@Html.ActionLink("Edit Dine Time", "EditDineTime", new { id = data.Id })*@
                                                        </td>
                                                        <td class="align-middle">
                                                            <a class="btn btn-danger btn-xs" href="~/DineTime/DeleteDineTime/@data.Id">
                                                                <i class="fa fa-trash-o"></i>
                                                            </a>
                                                            @*@Html.ActionLink("Delete Dine Time", "DeleteDineTime", new { id = data.Id })*@
                                                        </td>
                                                    </tr>

                                                    i = i + 1;
                                                }
                                            }
                                        </tbody>
                                    </table>
                                    <input type="hidden" id="notice" value="@TempData["notice"]" />
                                </div>

                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->


        @RenderPage("~/Views/Shared/_Footer.cshtml")

        <script>

            if ($('#notice').val() != '') {
                tempAlert($('#notice').val(), 2000);
            }

            function search_DineTime() {
                var a = $('#search_value').val();
                window.location.href = "/DineTime/List?search=" + a;
            }
        </script>