QolaMVC/Controllers/SuiteController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QolaMVC.DAL;
using QolaMVC.Models;

namespace QolaMVC.Controllers
{
    public class SuiteController : Controller
    {
        // GET: Suite
        public ActionResult List(string search,string column="*", string value="0")
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];
            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;
            TempData.Keep("User");
            TempData.Keep("Home");

            TempData.Keep("Resident");
            List<NEW_SuiteModel> l_Model;
            if (search==null || search == "")
            {
                l_Model = SuiteDAL.GetSuite_mike(string.Empty);
                TempData["search"] = "";
            }
            //List<NEW_SuiteModel> l_Model = SuiteDAL.GetAllSuite();
            else
            {
                l_Model = SuiteDAL.GetSuite_mike(search);
                TempData["search"] = search;
            }
            TempData["start"] = "1";
            return View(l_Model);
            
        }

        public ActionResult GetListByColumn(string column, string value)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            List<NEW_SuiteModel> l_Model = SuiteDAL.GetSuite_By_Column(column, value);
            return View(l_Model);
            //return View();
        }

        // GET: Suite/Create
        public ActionResult AddSuite()
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            Collection<HomeModel> l_Homes = HomeDAL.GetHomeCollections();
            ViewBag.Homes = l_Homes;
            return View();
        }

        // POST: Suite/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSuite(NEW_SuiteModel add_tbl_suite)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;


            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            if (ModelState.IsValid)
            {
                SuiteDAL.AddSuite(add_tbl_suite,user.ID);
                TempData["notice"] = "Add Successfully";
                return RedirectToAction("List");
            }
            else
            {
                TempData["notice"] = "Add Failed";
                return RedirectToAction("List");
            }
            

        }

        // GET: Suite/Edit/5
        public ActionResult EditSuite(int id)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;


            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            Collection<HomeModel> l_Homes = HomeDAL.GetHomeCollections();
            ViewBag.Homes = l_Homes;
            return View(SuiteDAL.GetSuite_By_Id(id));
            //List<NEW_SuiteModel> l_Model = SuiteDAL.GetSuite_By_Id(id);
            //return View(l_Model);
            //return View();
        }

        // POST: Suite/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSuite(int id, NEW_SuiteModel suite)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            if (ModelState.IsValid)
            {
                SuiteDAL.EditSuite(suite, id);
                TempData["notice"] = "Edit Successfully";
                return RedirectToAction("List");
            }
            else
            {
                TempData["notice"] = "Edit Failed";
                return RedirectToAction("List");
            }
                
        }

        // GET: Suite/Delete/5
        public ActionResult DeleteSuite(int id)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View(SuiteDAL.GetSuite_By_Id(id));
        }

        // POST: Suite/Delete/5
        [HttpPost]
        public ActionResult DeleteSuite(int id, FormCollection collection)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            try
            {
                // TODO: Add delete logic here

                SuiteDAL.DeleteSuite(id);
                TempData["notice"] = "Delete Successfully";
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult GetSuiteList(int index, string search)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];
            List<NEW_SuiteModel> l_Model;
            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");
            if (search == null || search == "")
            {
                l_Model = SuiteDAL.GetSuite_mike(string.Empty);
            }
            //List<NEW_SuiteModel> l_Model = SuiteDAL.GetAllSuite();
            else
            {
                l_Model = SuiteDAL.GetSuite_mike(search);
            }
            List<dynamic> l_Json = new List<dynamic>();

            for (int a = (index - 1) * 50; a < index * 50; a++)
            {
                if (a < l_Model.Count())
                {
                    dynamic l_J = new System.Dynamic.ExpandoObject();
                    l_J.ID = l_Model[a].Id;
                    l_J.Home = l_Model[a].Home;
                    l_J.HomeID = l_Model[a].HomeID;
                    l_J.Suite_No = l_Model[a].Suite_No;
                    l_J.Floor_No = l_Model[a].Floor_No;
                    l_J.No_Of_Rooms = l_Model[a].No_Of_Rooms;
                    l_Json.Add(l_J);
                }

            }
            return Json(l_Json, JsonRequestBehavior.AllowGet);
        }


    }
}

QolaMVC/Views/Suite/AddSuite.cshtml
@model QolaMVC.Models.NEW_SuiteModel

@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
    .required_sign {
        color: red;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-9">
                            <h3>@QolaMVC.Resources.Text.AddSuite</h3>
                        </div>
                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("AddSuite", "Suite", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.Home_Name<span class="required_sign">&nbsp;*</span></label>
                                                <select name="HomeID" class="form-control">
                                                    @{
                                                        foreach (var l_Home in (IEnumerable<QolaMVC.Models.HomeModel>)ViewBag.Homes)
                                                        {
                                                            <option value="@l_Home.Id">@l_Home.Name</option>
                                                        }
                                                    }
                                                </select>
                                                @*@Html.TextBoxFor(m => m.Home, new { @class = "form-control" })*@
                                                @Html.ValidationMessageFor(m => m.HomeID, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.SuiteNo<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.Suite_No, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Suite_No, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.FloorNo<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.Floor_No, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Floor_No, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.numberofRooms<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.No_Of_Rooms, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.No_Of_Rooms, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "Suite")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Save_big</button>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")
        <script>
            $('form').submit(function (event) {
                if ($('#Suite_No').val().trim() == '' || $('#Floor_No').val().trim() == '' || $('#No_Of_Rooms').val().trim() == '') {
                    tempAlert("Mandatory Needed", 2000);
                    return false;

                }
                else if ($.isNumeric($('#Floor_No').val().trim()) == false) {
                    tempAlert("Floor No. need a number", 2000);
                    return false;
                }
                else if (parseInt($('#Floor_No').val().trim()) > 127) {
                    tempAlert("Floor No. too large", 2000);
                    return false;
                }
                else if ($.isNumeric($('#No_Of_Rooms').val().trim()) == false) {
                    tempAlert("Room No. need a number", 2000);
                    return false;
                }
                else if (parseInt($('#No_Of_Rooms').val().trim()) > 127) {
                    tempAlert("Room No. too large", 2000);
                    return false;
                }

                else {
                    form = this;
                    form.submit();
                }
            });
        </script>

QolaMVC/Views/Suite/DeleteSuite.cshtml
@model QolaMVC.Models.NEW_SuiteModel
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-9">
                            <h3>@QolaMVC.Resources.Text.AreYouSureYouWantToDeleteThisRecord</h3>
                        </div>
                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("DeleteSuite", "Suite", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.Home_Name</label>
                                            <label class="form-control" style="width:70%;">@Model.Home</label>
                                            @*@Html.TextBoxFor(m => m.Home, new { @class = "form-control" })*@
                                            @Html.ValidationMessageFor(m => m.Home, null, new { @style = "color: red; font-style: italic;" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.SuiteNo</label>
                                            <label class="form-control" style="width:70%;">@Model.Suite_No</label>
                                            @*@Html.TextBoxFor(m => m.Suite_No, new { @class = "form-control" })*@
                                            @Html.ValidationMessageFor(m => m.Suite_No, null, new { @style = "color: red; font-style: italic;" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.FloorNo</label>
                                            <label class="form-control" style="width:70%;">@Model.Floor_No</label>
                                            @*@Html.TextBoxFor(m => m.Floor_No, new { @class = "form-control" })*@
                                            @Html.ValidationMessageFor(m => m.Floor_No, null, new { @style = "color: red; font-style: italic;" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.numberofRooms</label>
                                            <label class="form-control" style="width:70%;">@Model.No_Of_Rooms</label>
                                            @*@Html.TextBoxFor(m => m.No_Of_Rooms, new { @class = "form-control" })*@
                                            @Html.ValidationMessageFor(m => m.No_Of_Rooms, null, new { @style = "color: red; font-style: italic;" })
                                        </div>
                                    </div>
                                </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "Suite")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Delete_big</button>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")

QolaMVC/Views/Suite/EditSuite.cshtml
@model QolaMVC.Models.NEW_SuiteModel
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
    .required_sign {
        color: red;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")

    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-9">
                            <h3>@QolaMVC.Resources.Text.EditSuite</h3>
                        </div>
                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->

            <div style="height: 60px;"></div>

            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->


                <div class="card">
                    <div class="card-block">

                        <div class="row">
                            <div class="col-md-8 offset-md-2">
                                @using (Html.BeginForm("EditSuite", "Suite", new { p_ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.Home_Name<span class="required_sign">&nbsp;*</span></label>
                                                <select name="HomeID" class="form-control">
                                                    @{
                                                        foreach (var l_Home in (IEnumerable<QolaMVC.Models.HomeModel>)ViewBag.Homes)
                                                        {
                                                            if (Model != null && Model.HomeID == l_Home.Id)
                                                            {
                                                                <option value="@l_Home.Id" selected>@l_Home.Name</option>
                                                            }
                                                            else
                                                            {
                                                                <option value="@l_Home.Id">@l_Home.Name</option>
                                                            }
                                                        }
                                                    }
                                                </select>
                                                @*@Html.TextBoxFor(m => m.Home, new { @class = "form-control" })*@
                                                @Html.ValidationMessageFor(m => m.HomeID, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.SuiteNo<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.Suite_No, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Suite_No, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.FloorNo<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.Floor_No, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Floor_No, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="staticEmail" class="col-form-label">@QolaMVC.Resources.Text.numberofRooms<span class="required_sign">&nbsp;*</span></label>
                                                @Html.TextBoxFor(m => m.No_Of_Rooms, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.No_Of_Rooms, null, new { @style = "color: red; font-style: italic;" })
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("List", "Suite")'" value="@QolaMVC.Resources.Text.Back_big">
                                            <button class="btn btn-danger btn-lg">@QolaMVC.Resources.Text.Update_big</button>
                                            @*<input type="reset" class="btn btn-danger btn-lg" value="CLEAR">*@
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>


                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->




        @RenderPage("~/Views/Shared/_Footer.cshtml")
        <script>
            $('form').submit(function (event) {
                if ($('#Suite_No').val().trim() == '' || $('#Floor_No').val().trim() == '' || $('#No_Of_Rooms').val().trim() == '') {
                    tempAlert("Mandatory Needed", 2000);
                    return false;

                }
                else if ($.isNumeric($('#Floor_No').val().trim()) == false) {
                    tempAlert("Floor No. need a number", 2000);
                    return false;
                }
                else if (parseInt($('#Floor_No').val().trim()) >127) {
                    tempAlert("Floor No. too large", 2000);
                    return false;
                }
                else if ($.isNumeric($('#No_Of_Rooms').val().trim()) == false) {
                    tempAlert("Room No. need a number", 2000);
                    return false;
                }
                else if (parseInt($('#No_Of_Rooms').val().trim()) >127) {
                    tempAlert("Room No. too large", 2000);
                    return false;
                }

                else {
                    form = this;
                    form.submit();
                }
            });
        </script>