QolaMVC/Models/CUOL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class CUOL
    {
        public int Id { get; set; }
        public int HomeID { get; set; }
        public ResidentModel Resident { get; set; }
        public string Amount { get; set; }
        public string Color { get; set; }
        public string Comments { get; set; }
        public string userName { get; set; }
        public string userNameType { get; set; }
        public UserModel EnteredBy { get; set; }
        public DateTime TimeStamp { get; set; }
    }
}

QolaMVC/Models/MRAF.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class MRAF
    {
        public int Id { get; set; }
        public int HomeId { get; set; }
        public int ResidentId { get; set; }
        public int EnteredBy { get; set; }
        public DateTime DateEntered { get; set; }
        public string DateEnteredString { get; set; }
        public string BriefHistory { get; set; }
        public string DescriptionBehaviour { get; set; }
        public string DescriptionRisk { get; set; }
        public string RiskAgreement { get; set; }
        public string GoalsRisk  { get; set; }
        public string Termunder { get; set; }
        public string Stafftraining  { get; set; }

        public string ImplementationDate { get; set; }
        public string ScheduledReviewDate { get; set; }
        public string FollowupReviewDate { get; set; }
        public string GuardianName { get; set; }
        public string TrusteeName { get; set; }
        public string GuardianAgentName { get; set; }
        public string ServiceProviderName { get; set; }
        public string ClientCareName { get; set; }
        public string Copy1 { get; set; }
        public string Copy2 { get; set; }

    }
}

QolaMVC/Models/OCCC.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class OCCC
    {
        public int ID { get; set; }
        public int homeID { get; set; }
        public int residentID { get; set; }
        public bool checkYes1 { get; set; }
        public bool checkNo1 { get; set; }
        public bool checkYes2 { get; set; }
        public bool checkNo2 { get; set; }
        public bool checkYes3 { get; set; }
        public bool checkNo3 { get; set; }
        public bool checkYes4 { get; set; }
        public bool checkNo4 { get; set; }
        public bool checkYes5 { get; set; }
        public bool checkNo5 { get; set; }
        public bool checkYes6 { get; set; }
        public bool checkNo6 { get; set; }
        public bool checkYes7 { get; set; }
        public bool checkNo7 { get; set; }
        public bool checkYes8 { get; set; }
        public bool checkNo8 { get; set; }
        public bool checkYes9 { get; set; }
        public bool checkNo9 { get; set; }
        public string Location { get; set; }
        public string comments { get; set; }
        public string userName { get; set; }
        public string userNameType { get; set; }
        public int modified_by { get; set; }
        public DateTime dtmTimeStamp { get; set; }
    }
}

QolaMVC/Models/OCTF.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class OCTF
    {
        public int Id { get; set; }
        public int homeID { get; set; }
        public int ResidentID { get; set; }
        public string Type { get; set; }
        public string AssessmentResult { get; set; }
        public string LevelProtocol { get; set; }
        public string LevelOfAssistance { get; set; }
        public string Initials { get; set; }
        public string Comments { get; set; }
        public int EnteredBy { get; set; }
        public DateTime TimeStamp { get; set; }
        public string userName { get; set; }
        public string userNameType { get; set; }
    }
}

QolaMVC/Models/SBSWTL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class SBSWTL
    {
        public int ID { get; set; }
        public int residentID { get; set; }
        public List<SBSWTL_row> SBSWTL_List { get; set; }
        public DateTime start_time { get; set; }
        public int modified_by { get; set; }
        public DateTime modified_on { get; set; }
    }
}

QolaMVC/Models/WCFS_protocol.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QolaMVC.Models
{
    public class WCFS_protocol
    {
        public int Id { get; set; }
        public int currentWound { get; set; }
        public int totalWound { get; set; }
        public DateTime dateEntered { get; set; }
        public int EnteredBy { get; set; }

        public string Wound_Image_Location1 { get; set; }
        public string Wound_Image_Location2 { get; set; }

        public bool Wound_Type_Pressure { get; set; }
        public bool Wound_Type_Arterial { get; set; }
        public bool Wound_Type_Venous { get; set; }
        public bool Wound_Type_SurgicalWound { get; set; }
        public bool Wound_Type_SkinTear { get; set; }
        public bool Wound_Type_Other { get; set; }
        public string Wound_Type_Other_Text { get; set; }

        public DateTime Wound_Protocol_Date { get; set; }
        public string Wound_Protocol_Frequency { get; set; }
        public string Wound_Protocol_Initiated { get; set; }
        public string Wound_Protocol_Protocol_Text { get; set; }

        public bool Wound_HCA_Yes { get; set; }
        public bool Wound_HCA_No { get; set; }
        public DateTime Wound_HCA_initial_Date{ get; set; }
        public string Wound_HCA_Assigned_by { get; set; }

    }
}

QolaMVC/Controllers/AssessmentsController.cs
using QolaMVC.DAL;
using QolaMVC.EF_DAL;
using QolaMVC.Helpers;
using QolaMVC.Models;
using QolaMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using System.Data;
using System.Data.SqlClient;
using System.Web.Script;
using System.Web.Script.Serialization;
using System.Reflection;
using Newtonsoft.Json;
using System.Text;

namespace QolaMVC.Controllers
{
    public class AssessmentsController : Controller
    {
        // GET: Assessments
        public ActionResult Index()
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");
            if(TempData["archive"] != null && TempData["archive"].ToString() == "YES")
            {
                TempData["archive"] = "YES";
            }
            else
            {
                TempData["archive"] = "NO";
            }


            return View();
        }

        public ActionResult Index2()
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            TempData["archive"] = "YES";

            return View("Index");
        }

        public ActionResult BowelMovement()
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            if(TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;
            ViewBag.ReturnUrl = "/Assessments/BowelMovement";

            var bowelMovement = new BowelMovementModel();
            bowelMovement.Resident = resident;
            bowelMovement.EnteredBy = user;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            return View(bowelMovement);
        }

        [HttpPost]
        public ActionResult AddBowelMovement(BowelMovementModel p_BowelMovement, string p_ReturnUrl)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;
            
            p_BowelMovement.Resident = resident;
            p_BowelMovement.EnteredBy = user;
            DataErrorInfoModelValidatorProvider dataErrorInfoModelValidatorProvider = new DataErrorInfoModelValidatorProvider();
            
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            AssessmentDAL.AddNewBowelMovement(p_BowelMovement);
            TempData["Message"] = "Added Bowel Assessment";
            return Redirect(p_ReturnUrl);
        }

        public ActionResult DietaryHistory(string index, string ack= "",int daID = 0)
        {
            TempData["ack"] = ack;

            var user = (UserModel)TempData["User"];
            var home = (HomeModel)TempData["Home"];
            var resident = (ResidentModel)TempData["Resident"];
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");
            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;


            var l_DietaryAssessment = AssessmentDAL.GetResidentDietaryAssesments(resident.ID);
            if (l_DietaryAssessment.Count == 0)
            {
                l_DietaryAssessment = new Collection<nDietaryAssessmentModel>();
                nDietaryAssessmentModel l_Dietary = new nDietaryAssessmentModel();

                Collection<AllergiesModel> allergySampleCollection = new Collection<AllergiesModel>();
                AllergiesModel allergySample = new AllergiesModel();
                allergySampleCollection.Add(allergySample);
                l_Dietary.Allergies = allergySampleCollection;
                l_DietaryAssessment.Add(l_Dietary);
            }
            List<DateTime> l_AssessmentDates = new List<DateTime>();
            foreach (var l_A in l_DietaryAssessment)
            {
                l_AssessmentDates.Add(l_A.DateEntered);
            }
            ViewBag.AssessmentDates = l_AssessmentDates;

            nDietaryAssessmentModel single = new nDietaryAssessmentModel();

            if (ack == "true")
            {
                foreach (var assessment in l_DietaryAssessment)
                {
                    if (assessment.Id == daID)
                    {
                        single = assessment;
                        TempData["actDate"] = single.DateEntered.ToString("yyyy-MM-dd");
                    }
                }
            }
            else
            {
                if (index == null || index == "")
                {
                    TempData["index"] = "0";
                    single = l_DietaryAssessment[0];
                }
                else
                {
                    TempData["index"] = index;
                    single = l_DietaryAssessment[int.Parse(index)];
                }
                TempData["actDate"] = "";
            }
            

           


            TempData.Keep("index");
            ViewBag.AssessmentDates = l_AssessmentDates;
            //return View(l_DietaryAssessment.LastOrDefault());
            QolaCulture.InitDiets(ref single);
            if (single.Diet != null)
            {
                foreach (var str in single.Diet)
                {
                    for (int check = 0; check < single.Diet2.Count(); check++)
                    {
                        if (str == single.Diet2[check].Name)
                        {
                            single.Diet2[check].IsSelected = true;
                        }
                    }
                }
            }

            return View(single);
        }

        public ActionResult DietaryHistory2(int p_ResidentId)
        {
            var user = (UserModel)TempData["User"];
            var home = (HomeModel)TempData["Home"];
            var resident = ResidentsDAL.GetResidentById(p_ResidentId);
            var progressNotes = ProgressNotesDAL.GetProgressNotesCollections(resident.ID, DateTime.Now, DateTime.Now, "A");
            ViewBag.Message = TempData["Message"];
            TempData["Resident"] = resident;
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");
            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;
            ViewBag.ProgressNotes = progressNotes;
            ProgressNotesHelper.RegisterSession(resident);

            

            return RedirectToAction("DietaryHistory");
        }

        public ActionResult DietaryHistory3(int p_ResidentId, int da)
        {
            var user = (UserModel)TempData["User"];
            var home = (HomeModel)TempData["Home"];
            var resident = ResidentsDAL.GetResidentById(p_ResidentId);
            var progressNotes = ProgressNotesDAL.GetProgressNotesCollections(resident.ID, DateTime.Now, DateTime.Now, "A");
            ViewBag.Message = TempData["Message"];
            TempData["Resident"] = resident;
            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");
            ViewBag.User = user;
            ViewBag.Home = home;
            ViewBag.Resident = resident;
            ViewBag.ProgressNotes = progressNotes;
            ProgressNotesHelper.RegisterSession(resident);



            return RedirectToAction("DietaryHistory", new { ack = "true", daID= da });
        }




        public ActionResult AddDietaryAssessment(nDietaryAssessmentModel p_Model)
        {
            var home = (HomeModel)TempData["Home"];
            var user = (UserModel)TempData["User"];
            var resident = (ResidentModel)TempData["Resident"];

            ViewBag.User = user;
            ViewBag.Resident = resident;
            ViewBag.Home = home;

            TempData.Keep("User");
            TempData.Keep("Home");
            TempData.Keep("Resident");

            p_Model.EnteredBy = user;
            p_Model.Resident = resident;
            p_Model.DateEntered = DateTime.Now;

            foreach (PropertyInfo prop in typeof(nDietaryAssessmentModel).GetProperties())
            {
                if (prop.PropertyType.Name == "String" || prop.PropertyType.Name == "string")
                {
                    if (prop.GetValue(p_Model) == null) { prop.SetValue(p_Model, ""); }
                }
            }
            p_Model.Diet = new Collection<string>();
            foreach(var check in p_Model.Diet2)
            {
                if (check.IsSelected == true)
                {
                    p_Model.Diet.Add(check.Name);
                }
            }

            var l_DietaryAssessment = AssessmentDAL.GetResidentDietaryAssesments(resident.ID);
            if (l_DietaryAssessment.Count >= 1)
            {
                if (l_DietaryAssessment[0].Appetite != p_Model.Appetite) p_Model.DIFF = p_Model.DIFF + "Appetite,";

QolaMVC/Views/Assessments/CUOL.cshtml
@RenderPage("~/Views/Shared/_Header.cshtml")
@RenderPage("~/Views/Shared/_SideBar.cshtml")
<script src="~/Content/jscolor/jscolor.js"></script>
<style>

    .form-tabs .nav-link {
        font-size: 1rem;
    }

    .modal-xlg {
        width: 900px !important;
        max-width: 1000px !important;
    }
    .required_sign {
        color: red;
    }
</style>
<!-- START PAGE-CONTAINER -->
<div class="page-container">

    @RenderPage("~/Views/Shared/_NavBar.cshtml")
    <!-- START PAGE CONTENT WRAPPER -->
    <div class="page-content-wrapper">
        <!-- START PAGE CONTENT -->
        <div class="content">
            <!-- START JUMBOTRON -->
            <div class="jumbotron w-100" style="position: fixed; z-index: 400">
                <div class="container-fluid container-fixed-lg">
                    <!-- <div class="inner"> -->
                    <div class="row align-items-center">
                        <div class="col-md-10">
                            <h3>Catheter Urine Output Log</h3>
                        </div>
                        <div class="col-md-1">
                            <a href="~/Assessments/" class="btn btn-primary"><i class="fa fa-backward"></i>Back</a>

                        </div>
                    </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- END JUMBOTRON -->
            <div style="height: 60px;"></div>
            <!-- START CONTAINER FLUID -->
            <div class="container-fluid container-fixed-lg">
                <!-- BEGIN PlACE PAGE CONTENT HERE -->
                @{
                    if (ViewBag.Message != null && ViewBag.Message != string.Empty)
                    {
                        <div class="alert alert-success" role="alert">
                            <button class="close" data-dismiss="alert"></button>
                            <strong>Success: </strong> @ViewBag.Message
                        </div>
                    }
                }

                @using (Html.BeginForm("AddCUOL", "Assessments", FormMethod.Post, new { @class = "p-t-15", @role = "form" }))
                {
                    <div class="card">
                        <div class="card-block">
                            <div class="row">
                                <div class="col-2">
                                    <label for="" class="col-form-label"><b>Resident: </b></label>
                                    <label>@ViewBag.Resident.FirstName @ViewBag.Resident.LastName </label>
                                </div>
                                <div class="col-2">
                                    <label for="" class="col-form-label"><b>Suite No: </b></label>
                                    <label>@ViewBag.Resident.SuiteNo</label>
                                </div>

                                <div style="width:99%;"><hr></div>
                                
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="" class="col-form-label">Amount<span class="required_sign">&nbsp;*</span></label>
                                        <input class="form-control" name="Amount"/>

                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="" class="col-form-label">Color</label>
                                        @*<input class="form-control" name="Color" type="color" />*@
                                        @*<input class="jscolor {hash:true} jscolor-active form-control" name="Color" value="" autocomplete="off" style="background-image: none;">*@
                                        <input class="form-control" name="Color" value="" >
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="" class="col-form-label">Comments</label>
                                        <textarea class="form-control" name="Comments" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>
                            <br><br>

                            <div class="row">
                                <div class="col-md-4 text-left">                            
                                </div>
                                <div class="col-md-7 text-right">
                                    <a href="~/Reports/CUOLReport" class="btn btn-success btn-lg">PREVIEW REPORT</a>
                                    <button class="btn btn-danger btn-lg">SAVE</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <!-- END PLACE PAGE CONTENT HERE -->
            </div>
            <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->
        @RenderPage("~/Views/Shared/_Footer.cshtml")
        <script>
            $('form').submit(function (event) {
                if ($('input[name="Amount"]').val().trim() == '') {
                    tempAlert("Amount Needed", 2000);
                    return false;

                }
                else {
                    form = this;
                    form.submit();
                }
            });
        </script>